# stations.py

# List of station names used by the app
STATIONS = [
    "Jamalpur", "Durgapur", "Mymensingh", "B. Baria", "Habiganj", "Bhairabbazar",
    "Derai", "Khaliajuri", "Manu-RB", "Moulvibazar", "Narsingdi", "Sheola",
    "Sherpur-Sylhet", "Sunamganj", "Sylhet"
]
# stations.py
def get_station_name_by_id(station_id):
    for station in STATION_MAPPING:
        if station["id"] == station_id:
            return station["name"]
    return f"Unknown ID {station_id}"

# Full station‐metadata mapping (as a Python list of dicts)
# This mapping is provided for context but not directly used in the current graphing feature beyond the STATIONS list.
# It could be used for future enhancements like showing danger levels or more station details.
STATION_MAPPING = [
    {
        "id": 1,
        "coords": "774,970",
        "name": "Chiringa",
        "river": "Matamuhuri",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "5.80",
        "riverhighestwaterlevel": "7.36",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Cox's Bazar",
        "upazilla": "Chakaria",
        "union": "Baraitali",
        "long": "92.079743",
        "order_up_down": 8,
        "lat": "21.773552",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 83,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 7.28,
        "date_of_rhwl": "2023-08-08"
    },
    {
        "id": 2,
        "coords": "798,965",
        "name": "Lama",
        "river": "Matamuhuri",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "11.80",
        "riverhighestwaterlevel": "15.00",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Bandarban",
        "upazilla": "Lama",
        "union": "",
        "long": "92.209356",
        "order_up_down": 7,
        "lat": "21.793554",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 82,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.92,
        "date_of_rhwl": "1999-08-12"
    },
    {
        "id": 4,
        "coords": "769,895",
        "name": "Dohazari",
        "river": "Sangu",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "6.55",
        "riverhighestwaterlevel": "8.14",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Chittagong",
        "upazilla": "Chandanaish",
        "union": "Hashimpur",
        "long": "92.063472",
        "order_up_down": 6,
        "lat": "22.157910",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 81,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 7.63,
        "date_of_rhwl": "2019-07-14"
    },
    {
        "id": 6,
        "coords": "798,887",
        "name": "Bandarban",
        "river": "Sangu",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "14.80",
        "riverhighestwaterlevel": "20.24",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Bandarban",
        "upazilla": "Bandarban Sadar",
        "union": "Kuhalong",
        "long": "92.216246",
        "order_up_down": 5,
        "lat": "22.194878",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 80,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 20.34,
        "date_of_rhwl": "1997-07-12"
    },
    {
        "id": 8,
        "coords": "322,839",
        "name": "Mongla",
        "river": "Passur",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "1.60",
        "riverhighestwaterlevel": "3.74",
        "pmdl": None,
        "river_chainage": "PUSSUR(16835.00)",
        "division": "Khulna",
        "district": "Bagerhat",
        "upazilla": "Mongla",
        "union": "Paurashava",
        "long": "89.594985",
        "order_up_down": 29,
        "lat": "22.460340",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 3.33,
        "date_of_rhwl": "1996-04-18"
    },
    {
        "id": 10,
        "coords": "729,817",
        "name": "Panchpukuria",
        "river": "Halda",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "9.05",
        "riverhighestwaterlevel": "12.08",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Chittagong",
        "upazilla": "Fatikchhari",
        "union": "Samitirhat",
        "long": "91.846427",
        "order_up_down": 4,
        "lat": "22.560860",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 79,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.46,
        "date_of_rhwl": "2003-06-27"
    },
    {
        "id": 11,
        "coords": "528,808",
        "name": "Daulatkhan",
        "river": "Lower Meghna",
        "basin_order": 3,
        "basin": "Megghna Basin",
        "dangerlevel": "2.95",
        "riverhighestwaterlevel": "5.11",
        "pmdl": None,
        "river_chainage": "SHAHABAZ-1(17000.00)",
        "division": "Barisal",
        "district": "Bhola",
        "upazilla": "Daulatkhan",
        "union": "Char Pata",
        "long": "90.736860",
        "order_up_down": 30,
        "lat": "22.615762",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 4.03,
        "date_of_rhwl": "1970-11-13"
    },
    {
        "id": 12,
        "coords": "208,808",
        "name": "Shakra",
        "river": "Ichamati",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "3.50",
        "riverhighestwaterlevel": "4.23",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Satkhira",
        "upazilla": "Debhata",
        "union": "Parulia",
        "long": "88.969965",
        "order_up_down": 27,
        "lat": "22.617779",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 47,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 13,
        "coords": "706,768",
        "name": "Narayanhat",
        "river": "Halda",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "14.80",
        "riverhighestwaterlevel": "17.64",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Chittagong",
        "upazilla": "Fatikchhari",
        "union": "Narayanhat",
        "long": "91.719765",
        "order_up_down": 3,
        "lat": "22.807724",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 78,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 16.92,
        "date_of_rhwl": "2003-06-26"
    },
    {
        "id": 14,
        "coords": "318,770",
        "name": "Khulna",
        "river": "Rupsa",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "2.60",
        "riverhighestwaterlevel": "3.29",
        "pmdl": None,
        "river_chainage": "RUPSA(4500.00)",
        "division": "Khulna",
        "district": "Khulna",
        "upazilla": "Khalishpur Thana",
        "union": "Paurashava",
        "long": "89.580462",
        "order_up_down": 26,
        "lat": "22.808223",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 3.49,
        "date_of_rhwl": "2013-08-22"
    },
    {
        "id": 15,
        "coords": "222,757",
        "name": "Kalaroa",
        "river": "Betna",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "3.35",
        "riverhighestwaterlevel": "5.18",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Satkhira",
        "upazilla": "Kalaroa",
        "union": "Helatala",
        "long": "89.047524",
        "order_up_down": 25,
        "lat": "22.871623",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 4.74,
        "date_of_rhwl": "2004-09-17"
    },
    {
        "id": 17,
        "coords": "703,738",
        "name": "Ramgarh",
        "river": "Feni",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "16.90",
        "riverhighestwaterlevel": "20.78",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Chittagong",
        "upazilla": "Fatikchhari",
        "union": "Bagan Bazar",
        "long": "91.703954",
        "order_up_down": 2,
        "lat": "22.968128",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 84,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 19.85,
        "date_of_rhwl": "1988-11-07"
    },
    {
        "id": 18,
        "coords": "232,713",
        "name": "Jhikargacha",
        "river": "Kobadak",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "4.65",
        "riverhighestwaterlevel": "4.99",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Jessore",
        "upazilla": "Jhikargachha",
        "union": "Gadkhali",
        "long": "89.096763",
        "order_up_down": 23,
        "lat": "23.101868",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 50,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 4.94,
        "date_of_rhwl": "2000-10-07"
    },
    {
        "id": 19,
        "coords": "432,697",
        "name": "Madaripur",
        "river": "Arialkhan",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "3.75",
        "riverhighestwaterlevel": "5.34",
        "pmdl": None,
        "river_chainage": "ARIALKHAN(53000.00)",
        "division": "Dhaka",
        "district": "Madaripur",
        "upazilla": "Madaripur Sadar",
        "union": "Paurashava",
        "long": "90.209848",
        "order_up_down": 22,
        "lat": "23.187806",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 52,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 5.37,
        "date_of_rhwl": "1998-09-11"
    },
    {
        "id": 20,
        "coords": "510,688",
        "name": "Chandpur",
        "river": "Lower Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "3.55",
        "riverhighestwaterlevel": "4.89",
        "pmdl": "3.55",
        "river_chainage": "Lower_Meghna(17400.00)",
        "division": "Chittagong",
        "district": "Chandpur",
        "upazilla": "Chandpur Sadar",
        "union": "Paurashava",
        "long": "90.639487",
        "order_up_down": 18,
        "lat": "23.231690",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 76,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 5.11,
        "date_of_rhwl": "1998-09-09"
    },
    {
        "id": 21,
        "coords": "654,689",
        "name": "Parshuram",
        "river": "Muhuri",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "12.55",
        "riverhighestwaterlevel": "15.87",
        "pmdl": None,
        "river_chainage": "",
        "division": "Chittagong",
        "district": "Feni",
        "upazilla": "Parshuram",
        "union": "Mirzanagar",
        "long": "91.438231",
        "order_up_down": 1,
        "lat": "23.221259",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 77,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.79,
        "date_of_rhwl": "2018-06-13"
    },
    {
        "id": 22,
        "coords": "474,670",
        "name": "Sureshswar",
        "river": "Padma",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "4.00",
        "riverhighestwaterlevel": "5.48",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Shariatpur",
        "upazilla": "Naria",
        "union": "Kedarpur",
        "long": "90.439032",
        "order_up_down": 21,
        "lat": "23.320123",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 44,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 4.92,
        "date_of_rhwl": "1988-09-04"
    },
    {
        "id": 23,
        "coords": "611,641",
        "name": "Comilla",
        "river": "Gumti",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "11.30",
        "riverhighestwaterlevel": "13.10",
        "pmdl": "11.30",
        "river_chainage": "GUMTI(4000.00)",
        "division": "Chittagong",
        "district": "Comilla",
        "upazilla": "Comilla Sadar",
        "union": "Panchthubi",
        "long": "91.198390",
        "order_up_down": 17,
        "lat": "23.471078",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 74,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 24,
        "coords": "312,629",
        "name": "Kamarkhali",
        "river": "Gorai",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "7.75",
        "riverhighestwaterlevel": "8.91",
        "pmdl": None,
        "river_chainage": "GORAI(83200.00)",
        "division": "Khulna",
        "district": "Magura",
        "upazilla": "Magura Sadar",
        "union": "Kasundi",
        "long": "89.516256",
        "order_up_down": 20,
        "lat": "23.539828",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 46,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.61,
        "date_of_rhwl": "1988-09-10"
    },
    {
        "id": 25,
        "coords": "431,633",
        "name": "Bhagyakul",
        "river": "Padma",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "5.85",
        "riverhighestwaterlevel": "7.04",
        "pmdl": None,
        "river_chainage": "PADMA(54000.00)",
        "division": "Dhaka",
        "district": "Munshiganj",
        "upazilla": "Sreenagar",
        "union": "Baghra",
        "long": "90.206392",
        "order_up_down": 19,
        "lat": "23.511165",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 43,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 6.76,
        "date_of_rhwl": "1998-09-10"
    },
    {
        "id": 27,
        "coords": "364,616",
        "name": "Faridpur",
        "river": "Kumar",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "7.05",
        "riverhighestwaterlevel": "8.30",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Faridpur",
        "upazilla": "Faridpur Sadar",
        "union": "Aliabad",
        "long": "89.831691",
        "order_up_down": 18,
        "lat": "23.597854",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 51,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.7,
        "date_of_rhwl": "1988-09-03"
    },
    {
        "id": 28,
        "coords": "479,608",
        "name": "Hariharpara",
        "river": "Buriganga",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.35",
        "riverhighestwaterlevel": "8.57",
        "pmdl": None,
        "river_chainage": "BURIGANGA(40000.00)",
        "division": "Dhaka",
        "district": "Dhaka",
        "upazilla": "Keraniganj",
        "union": "Konda",
        "long": "90.473884",
        "order_up_down": 17,
        "lat": "23.638440",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.16,
        "date_of_rhwl": "1996-07-04"
    },
    {
        "id": 29,
        "coords": "573,609",
        "name": "Jibanpur",
        "river": "Gumti",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "8.05",
        "riverhighestwaterlevel": "9.52",
        "pmdl": None,
        "river_chainage": "Gumti(41000.00)",
        "division": "Chittagong",
        "district": "Comilla",
        "upazilla": "Debidwar",
        "union": "Debidwar",
        "long": "90.987282",
        "order_up_down": 15,
        "lat": "23.630910",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 30,
        "coords": "184,603",
        "name": "Chuadanga",
        "river": "Mathabhanga",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "11.60",
        "riverhighestwaterlevel": "12.21",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Chuadanga",
        "upazilla": "Chuadanga Sadar",
        "union": "Alokdia",
        "long": "88.832914",
        "order_up_down": 15,
        "lat": "23.668621",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 48,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.84,
        "date_of_rhwl": "1998-09-14"
    },
    {
        "id": 31,
        "coords": "489,604",
        "name": "Narayanganj",
        "river": "Lakhya",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.05",
        "riverhighestwaterlevel": "6.47",
        "pmdl": None,
        "river_chainage": "Lakhya(61000.00)",
        "division": "Dhaka",
        "district": "Narayanganj",
        "upazilla": "Narayanganj Sadar",
        "union": "Sumil Para",
        "long": "90.514175",
        "order_up_down": 22,
        "lat": "23.630486",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 23,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 5.62,
        "date_of_rhwl": "1998-09-10"
    },
    {
        "id": 32,
        "coords": "474,600",
        "name": "Dhaka",
        "river": "Buriganga",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.55",
        "riverhighestwaterlevel": "7.12",
        "pmdl": None,
        "river_chainage": "BURIGANGA(29500.00)",
        "division": "Dhaka",
        "district": "Dhaka",
        "upazilla": "Keraniganj",
        "union": "Subhadya",
        "long": "90.417675",
        "order_up_down": 21,
        "lat": "23.699017",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 21,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 6.69,
        "date_of_rhwl": "1988-09-04"
    },
    {
        "id": 33,
        "coords": "484,592",
        "name": "Demra",
        "river": "Balu",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.30",
        "riverhighestwaterlevel": "6.63",
        "pmdl": None,
        "river_chainage": "Balu(26500.00)",
        "division": "Dhaka",
        "district": "Dhaka",
        "upazilla": "Demra Thana",
        "union": "Demra Psa",
        "long": "90.498857",
        "order_up_down": 20,
        "lat": "23.723940",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 22,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 5.9,
        "date_of_rhwl": "1988-09-06"
    },
    {
        "id": 34,
        "coords": "348,585",
        "name": "Goalondo",
        "river": "Ganges",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "8.20",
        "riverhighestwaterlevel": "9.75",
        "pmdl": None,
        "river_chainage": "JAMUNA(235650.00)",
        "division": "Dhaka",
        "district": "Rajbari",
        "upazilla": "Goalanda",
        "union": "Debagram",
        "long": "89.778872",
        "order_up_down": 16,
        "lat": "23.768642",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 42,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 9.45,
        "date_of_rhwl": "1998-09-09"
    },
    {
        "id": 35,
        "coords": "454,579",
        "name": "Mirpur",
        "river": "Turag",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.50",
        "riverhighestwaterlevel": "7.89",
        "pmdl": None,
        "river_chainage": "TURAG(63750.00)",
        "division": "Dhaka",
        "district": "Dhaka",
        "upazilla": "Mirpur Thana",
        "union": "Mirpur",
        "long": "90.335992",
        "order_up_down": 19,
        "lat": "23.784416",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 24,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 7.22,
        "date_of_rhwl": "1988-09-04"
    },
    {
        "id": 36,
        "coords": "190,579",
        "name": "Hatboalia",
        "river": "Mathabhanga",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "14.05",
        "riverhighestwaterlevel": "14.67",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Chuadanga",
        "upazilla": "Alamdanga",
        "union": "Bhangabaria",
        "long": "88.857085",
        "order_up_down": 14,
        "lat": "23.787087",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 49,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.67,
        "date_of_rhwl": "1984-09-17"
    },
    {
        "id": 37,
        "coords": "387,565",
        "name": "Taraghat",
        "river": "Kaliganga",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "7.95",
        "riverhighestwaterlevel": "9.91",
        "pmdl": None,
        "river_chainage": "KALIGANGA(15000.00)",
        "division": "Dhaka",
        "district": "Manikganj",
        "upazilla": "Manikganj Sadar",
        "union": "Dighi",
        "long": "89.958068",
        "order_up_down": 18,
        "lat": "23.862486",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 26,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.62,
        "date_of_rhwl": "1988-09-03"
    },
    {
        "id": 38,
        "coords": "354,561",
        "name": "Aricha",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "8.95",
        "riverhighestwaterlevel": "10.30",
        "pmdl": None,
        "river_chainage": "JAMUNA(227000.00)",
        "division": "Dhaka",
        "district": "Manikganj",
        "upazilla": "Shibalaya",
        "union": "Teota",
        "long": "89.772772",
        "order_up_down": 17,
        "lat": "23.881297",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 14,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 9.9,
        "date_of_rhwl": "1998-09-09"
    },
    {
        "id": 39,
        "coords": "399,561",
        "name": "Jagir",
        "river": "Old Dhaleswari",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "7.80",
        "riverhighestwaterlevel": "9.50",
        "pmdl": None,
        "river_chainage": "DHALESWARI(66666.66)",
        "division": "Dhaka",
        "district": "Manikganj",
        "upazilla": "Manikganj Sadar",
        "union": "Jaigir",
        "long": "90.025397",
        "order_up_down": 16,
        "lat": "23.878853",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.15,
        "date_of_rhwl": "1988-09-03"
    },
    {
        "id": 40,
        "coords": "248,561",
        "name": "Gorai-RB",
        "river": "Gorai",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "12.30",
        "riverhighestwaterlevel": "13.19",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Kushtia",
        "upazilla": "Kumarkhali",
        "union": "Chapra",
        "long": "89.182899",
        "order_up_down": 13,
        "lat": "23.883877",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 45,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 12.91,
        "date_of_rhwl": "1988-09-02"
    },
    {
        "id": 41,
        "coords": "466,561",
        "name": "Tongi",
        "river": "Tongi Khal",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.65",
        "riverhighestwaterlevel": "7.38",
        "pmdl": None,
        "river_chainage": "TONGI_K(9000.00)",
        "division": "Dhaka",
        "district": "Gazipur",
        "upazilla": "Gazipur Sadar",
        "union": "Paurashava",
        "long": "90.401019",
        "order_up_down": 15,
        "lat": "23.881711",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 25,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 6.68,
        "date_of_rhwl": "1988-09-04"
    },
    {
        "id": 42,
        "coords": "573,526",
        "name": "Bhairabbazar",
        "river": "Upper Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "5.80",
        "riverhighestwaterlevel": "7.32",
        "pmdl": "5.80",
        "river_chainage": "UPPER_MEGHNA(27000.00)",
        "division": "Dhaka",
        "district": "Kishorganj",
        "upazilla": "Bhairab",
        "union": "Paurashava",
        "long": "90.991206",
        "order_up_down": 14,
        "lat": "24.045541",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 72,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 43,
        "coords": "219,525",
        "name": "Hardinge-RB",
        "river": "Ganges",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "13.80",
        "riverhighestwaterlevel": "14.73",
        "pmdl": None,
        "river_chainage": "GANGES(35250.00)",
        "division": "Rajshahi",
        "district": "Pabna",
        "upazilla": "Ishwardi",
        "union": "Pakshi",
        "long": "89.033520",
        "order_up_down": 12,
        "lat": "24.067640",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 41,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 14.33,
        "date_of_rhwl": "1998-09-10"
    },
    {
        "id": 44,
        "coords": "436,555",
        "name": "Nayarhat",
        "river": "Bangshi",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "6.85",
        "riverhighestwaterlevel": "9.44",
        "pmdl": None,
        "river_chainage": "BANGSHI(192000.00)",
        "division": "Dhaka",
        "district": "Tangail",
        "upazilla": "Mirzapur",
        "union": "Ajgana",
        "long": "90.230264",
        "order_up_down": 14,
        "lat": "23.911094",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 29,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.18,
        "date_of_rhwl": "1988-09-03"
    },
    {
        "id": 45,
        "coords": "136,464",
        "name": "Rajshahi",
        "river": "Ganges",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "18.05",
        "riverhighestwaterlevel": "19.54",
        "pmdl": None,
        "river_chainage": "GANGES-EXT(45000.00)",
        "division": "Rajshahi",
        "district": "Rajshahi",
        "upazilla": "Paba",
        "union": "Haripur",
        "long": "88.553699",
        "order_up_down": 11,
        "lat": "24.368824",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 40,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 19.47,
        "date_of_rhwl": "2010-09-13"
    },
    {
        "id": 46,
        "coords": "647,459",
        "name": "Habiganj",
        "river": "Khowai",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "9.05",
        "riverhighestwaterlevel": "11.84",
        "pmdl": "8.65",
        "river_chainage": "KHOWAI(18500.00)",
        "division": "Sylhet",
        "district": "Habiganj",
        "upazilla": "Baniachong",
        "union": "Umednagar",
        "long": "91.410342",
        "order_up_down": 13,
        "lat": "24.392752",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 64,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.0,
        "date_of_rhwl": "2024-08-21"
    },
    {
        "id": 47,
        "coords": "741,452",
        "name": "Manu-RB",
        "river": "Manu",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "17.55",
        "riverhighestwaterlevel": "19.96",
        "pmdl": "16.45",
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Maulvibazar",
        "upazilla": "Kulaura",
        "union": "Tilagaon",
        "long": "91.937553",
        "order_up_down": 12,
        "lat": "24.428089",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 61,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 19.17,
        "date_of_rhwl": "2000-05-28"
    },
    {
        "id": 48,
        "coords": "344,445",
        "name": "Serajganj",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "12.90",
        "riverhighestwaterlevel": "14.66",
        "pmdl": None,
        "river_chainage": "",
        "division": "Rajshahi",
        "district": "Sirajganj",
        "upazilla": "Sirajganj Sadar",
        "union": "Paurashava",
        "long": "89.718387",
        "order_up_down": 13,
        "lat": "24.470952",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 13,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 14.7,
        "date_of_rhwl": "1988-08-30"
    },
    {
        "id": 49,
        "coords": "712,439",
        "name": "Moulvibazar",
        "river": "Manu",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "11.30",
        "riverhighestwaterlevel": "12.79",
        "pmdl": "9.55",
        "river_chainage": "MANU(37100.00)",
        "division": "Sylhet",
        "district": "Maulvibazar",
        "upazilla": "Rajnagar",
        "union": "Kamar Chak",
        "long": "91.774876",
        "order_up_down": 11,
        "lat": "24.496424",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 62,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 12.49,
        "date_of_rhwl": "2024-08-22"
    },
    {
        "id": 50,
        "coords": "210,416",
        "name": "Atrai",
        "river": "Atrai",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "13.25",
        "riverhighestwaterlevel": "13.94",
        "pmdl": None,
        "river_chainage": "ATRAI(56587.00)",
        "division": "Rajshahi",
        "district": "Naogaon",
        "upazilla": "Atrai",
        "union": "Bhopara",
        "long": "88.965237",
        "order_up_down": 8,
        "lat": "24.622085",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 13.94,
        "date_of_rhwl": "2020-07-16"
    },
    {
        "id": 51,
        "coords": "83,419",
        "name": "C-Nawabganj",
        "river": "Mohananda",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "20.55",
        "riverhighestwaterlevel": "22.55",
        "pmdl": None,
        "river_chainage": "MOHANANDA(45875.00)",
        "division": "Rajshahi",
        "district": "Chapai Nawabganj",
        "upazilla": "Nawabganj Sadar",
        "union": "Balidanga",
        "long": "88.249526",
        "order_up_down": 9,
        "lat": "24.599517",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 36,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 52,
        "coords": "696,414",
        "name": "Sherpur-Sylhet",
        "river": "Kushiyara",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "8.55",
        "riverhighestwaterlevel": "9.22",
        "pmdl": "7.80",
        "river_chainage": "KUSHIYARA(91000.00)",
        "division": "Sylhet",
        "district": "Maulvibajar",
        "upazilla": "Maulvi Bazar Sadar",
        "union": "Khalilpur",
        "long": "91.681667",
        "order_up_down": 10,
        "lat": "24.628307",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 58,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.79,
        "date_of_rhwl": "2024-06-21"
    },
    {
        "id": 53,
        "coords": "472,394",
        "name": "Mymensingh",
        "river": "Old Brahmaputra",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "12.05",
        "riverhighestwaterlevel": "13.25",
        "pmdl": None,
        "river_chainage": "O_BRAMAPUTRA(127500.00)",
        "division": "Dhaka",
        "district": "Mymensingh",
        "upazilla": "Gauripur",
        "union": "Bhangnamari",
        "long": "90.431068",
        "order_up_down": 12,
        "lat": "24.737208",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 19,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 12.73,
        "date_of_rhwl": "1988-09-01"
    },
    {
        "id": 54,
        "coords": "171,359",
        "name": "Mohadevpur",
        "river": "Atrai",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "18.15",
        "riverhighestwaterlevel": "19.43",
        "pmdl": None,
        "river_chainage": "ATRAI(3170.00)",
        "division": "Rajshahi",
        "district": "Naogaon",
        "upazilla": "Manda",
        "union": "Bhalain",
        "long": "88.744249",
        "order_up_down": 7,
        "lat": "24.916416",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 38,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 55,
        "coords": "286,375",
        "name": "Bogra",
        "river": "Karatoa",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "15.85",
        "riverhighestwaterlevel": "16.99",
        "pmdl": None,
        "river_chainage": "LKARATOYA(0.00)",
        "division": "Rajshahi",
        "district": "Bogra",
        "upazilla": "Shajahanpur",
        "union": "Sultanganj",
        "long": "89.391511",
        "order_up_down": 11,
        "lat": "24.831299",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 7,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 56,
        "coords": "285,314",
        "name": "Chakrahimpur",
        "river": "Karatoa",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "19.70",
        "riverhighestwaterlevel": "20.95",
        "pmdl": None,
        "river_chainage": "KARATOYA(53536.00)",
        "division": "Rajshahi",
        "district": "Gaibandha",
        "upazilla": "Gobindaganj",
        "union": "Gobindaganj Psa",
        "long": "89.377776",
        "order_up_down": 10,
        "lat": "25.146083",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 6,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 20.95,
        "date_of_rhwl": "1980-08-23"
    },
    {
        "id": 57,
        "coords": "204,372",
        "name": "Naogaon",
        "river": "Little Jamuna",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "14.80",
        "riverhighestwaterlevel": "15.86",
        "pmdl": None,
        "river_chainage": "L-JAMUNA(12200.00)",
        "division": "Rajshahi",
        "district": "Naogaon",
        "upazilla": "Naogaon Sadar",
        "union": "Tilakpur",
        "long": "88.932033",
        "order_up_down": 6,
        "lat": "24.844091",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 37,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 15.73,
        "date_of_rhwl": "2005-10-07"
    },
    {
        "id": 58,
        "coords": "94,376",
        "name": "Rohanpur",
        "river": "Punarvaba",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "21.55",
        "riverhighestwaterlevel": "24.00",
        "pmdl": None,
        "river_chainage": "MOHANANDA(6500.00)",
        "division": "Rajshahi",
        "district": "Chapai Nawabganj",
        "upazilla": "Gomastapur",
        "union": "Bhangabaria",
        "long": "88.318746",
        "order_up_down": 5,
        "lat": "24.820982",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 35,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 23.65,
        "date_of_rhwl": "1998-09-11"
    },
    {
        "id": 59,
        "coords": "723,362",
        "name": "Sylhet",
        "river": "Surma",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "10.80",
        "riverhighestwaterlevel": "11.98",
        "pmdl": "8.30",
        "river_chainage": "SURMA(68300.00)",
        "division": "Sylhet",
        "district": "Sylhet",
        "upazilla": "Sylhet Sadar",
        "union": "Baraikandi",
        "long": "91.849452",
        "order_up_down": 9,
        "lat": "24.888834",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 54,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.69,
        "date_of_rhwl": "2022-06-18"
    },
    {
        "id": 60,
        "coords": "835,364",
        "name": "Amalshid",
        "river": "Kushiyara",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "15.40",
        "riverhighestwaterlevel": "17.82",
        "pmdl": "13.05",
        "river_chainage": "BARAK(0.00)",
        "division": "Sylhet",
        "district": "Sylhet",
        "upazilla": "Zakiganj",
        "union": "Bara Thakuri",
        "long": "92.475560",
        "order_up_down": 8,
        "lat": "24.869149",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 56,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 17.57,
        "date_of_rhwl": "2024-05-30"
    },
    {
        "id": 61,
        "coords": "784,362",
        "name": "Sheola",
        "river": "Kushiyara",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "13.05",
        "riverhighestwaterlevel": "14.14",
        "pmdl": "10.70",
        "river_chainage": "KUSHIYARA(0.00",
        "division": "Sylhet",
        "district": "Sylhet",
        "upazilla": "Beani Bazar",
        "union": "Sheola",
        "long": "92.190389",
        "order_up_down": 7,
        "lat": "24.887983",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 57,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 13.72,
        "date_of_rhwl": "2022-06-20"
    },
    {
        "id": 62,
        "coords": "386,354",
        "name": "Jamalpur",
        "river": "Old Brahmaputra",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "16.55",
        "riverhighestwaterlevel": "17.53",
        "pmdl": None,
        "river_chainage": "O_BRAMAPUTRA(63580.00)",
        "division": "Dhaka",
        "district": "Jamalpur",
        "upazilla": "Jamalpur Sadar",
        "union": "Char Pakshimari",
        "long": "89.967658",
        "order_up_down": 9,
        "lat": "24.923502",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 18,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 17.2,
        "date_of_rhwl": "1964-07-31"
    },
    {
        "id": 63,
        "coords": "510,340",
        "name": "Jariajanjail",
        "river": "Kangsha",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "10.55",
        "riverhighestwaterlevel": "12.91",
        "pmdl": "6.35",
        "river_chainage": "KANGSHA(62000.00)",
        "division": "Dhaka",
        "district": "Netrokona",
        "upazilla": "Durgapur",
        "union": "Kakairgara",
        "long": "90.652813",
        "order_up_down": 6,
        "lat": "25.009779",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 71,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.08,
        "date_of_rhwl": "2014-09-23"
    },
    {
        "id": 64,
        "coords": "798,339",
        "name": "Kanaighat",
        "river": "Surma",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "12.75",
        "riverhighestwaterlevel": "14.80",
        "pmdl": "10.90",
        "river_chainage": "SURMA(0.00)",
        "division": "Sylhet",
        "district": "Sylhet",
        "upazilla": "Kanaighat",
        "union": "Paschim Dighirpar",
        "long": "92.265191",
        "order_up_down": 4,
        "lat": "25.004479",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 53,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.63,
        "date_of_rhwl": "2012-06-16"
    },
    {
        "id": 65,
        "coords": "644,328",
        "name": "Sunamganj",
        "river": "Surma",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "7.80",
        "riverhighestwaterlevel": "9.29",
        "pmdl": "6.05",
        "river_chainage": "SURMA(160750.00)",
        "division": "Sylhet",
        "district": "Sunamganj",
        "upazilla": "Sunamganj Sadar",
        "union": "Paurashava",
        "long": "91.405531",
        "order_up_down": 3,
        "lat": "25.071634",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 55,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.0,
        "date_of_rhwl": "2022-06-17"
    },
    {
        "id": 66,
        "coords": "340,321",
        "name": "Bahadurabad",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "19.05",
        "riverhighestwaterlevel": "20.17",
        "pmdl": None,
        "river_chainage": "JAMUNA(84500.00)",
        "division": "Dhaka",
        "district": "Jamalpur",
        "upazilla": "Islampur",
        "union": "Belgachha",
        "long": "89.701110",
        "order_up_down": 8,
        "lat": "25.104949",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 11,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 20.63,
        "date_of_rhwl": "2019-07-18"
    },
    {
        "id": 67,
        "coords": "511,318",
        "name": "Durgapur",
        "river": "Someswari",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "12.55",
        "riverhighestwaterlevel": "15.12",
        "pmdl": "10.80",
        "river_chainage": "O_SOMESWARI(0.00)",
        "division": "Dhaka",
        "district": "Netrokona",
        "upazilla": "Durgapur",
        "union": "Kullagora",
        "long": "90.661579",
        "order_up_down": 5,
        "lat": "25.123256",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 70,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.98,
        "date_of_rhwl": "2007-07-28"
    },
    {
        "id": 68,
        "coords": "771,322",
        "name": "Sarighat",
        "river": "Sarigowain",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "12.35",
        "riverhighestwaterlevel": "14.02",
        "pmdl": "10.70",
        "river_chainage": "SARIGOWAIN(0.00)",
        "division": "Sylhet",
        "district": "Sylhet",
        "upazilla": "Gowainghat",
        "union": "Purba Jaflong",
        "long": "92.118330",
        "order_up_down": 2,
        "lat": "25.087706",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 60,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 13.53,
        "date_of_rhwl": "2024-05-30"
    },
    {
        "id": 69,
        "coords": "434,305",
        "name": "Nakuagaon",
        "river": "Bhugai",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "21.95",
        "riverhighestwaterlevel": "25.55",
        "pmdl": "20.80",
        "river_chainage": "BHUGAI(0.00)",
        "division": "Dhaka",
        "district": "Sherpur",
        "upazilla": "Nalitabari",
        "union": "Ramchandrakura Mandalia",
        "long": "90.220624",
        "order_up_down": None,
        "lat": "25.192257",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 68,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 25.0,
        "date_of_rhwl": "2011-08-16"
    },
    {
        "id": 70,
        "coords": "617,304",
        "name": "Lourergorh",
        "river": "Jadukata",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "8.05",
        "riverhighestwaterlevel": "11.39",
        "pmdl": "5.95",
        "river_chainage": "JADUKATA(0.00)",
        "division": "Sylhet",
        "district": "Sunamganj",
        "upazilla": "Tahirpur",
        "union": "Uttar Badal",
        "long": "91.250119",
        "order_up_down": 1,
        "lat": "25.191499",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 69,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 71,
        "coords": "312,274",
        "name": "Gaibandha",
        "river": "Ghagot",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "21.25",
        "riverhighestwaterlevel": "22.35",
        "pmdl": None,
        "river_chainage": "ALAI(0.00)",
        "division": "Rangpur",
        "district": "Gaibandha",
        "upazilla": "Gaibandha Sadar",
        "union": "Kholahati",
        "long": "89.534632",
        "order_up_down": 7,
        "lat": "25.352536",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 5,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 22.06,
        "date_of_rhwl": "2004-07-14"
    },
    {
        "id": 72,
        "coords": "340,236",
        "name": "Chilmari",
        "river": "Brahmaputra",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "23.25",
        "riverhighestwaterlevel": "24.61",
        "pmdl": None,
        "river_chainage": "JAMUNA(36100.00)",
        "division": "Rangpur",
        "district": "Kurigram",
        "upazilla": "Chilmari",
        "union": "Chilmari",
        "long": "89.686153",
        "order_up_down": 6,
        "lat": "25.544273",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 9,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 24.37,
        "date_of_rhwl": "1962-08-23"
    },
    {
        "id": 73,
        "coords": "170,191",
        "name": "Bhusirbandar",
        "river": "Upper Atrai",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "39.15",
        "riverhighestwaterlevel": "40.46",
        "pmdl": None,
        "river_chainage": "UATRAI(141500.00)",
        "division": "Rangpur",
        "district": "Dinajpur",
        "upazilla": "Chirirbdndar",
        "union": "Bhiail",
        "long": "88.731861",
        "order_up_down": 4,
        "lat": "25.767523",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 34,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 39.43,
        "date_of_rhwl": "1968-10-06"
    },
    {
        "id": 74,
        "coords": "148,228",
        "name": "Dinajpur",
        "river": "Punarbhaba",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "33.05",
        "riverhighestwaterlevel": "33.85",
        "pmdl": None,
        "river_chainage": "PUNARBHABA(50000.00)",
        "division": "Rangpur",
        "district": "Dinajpur",
        "upazilla": "Dinajpur Sadar",
        "union": "Chehelgazi",
        "long": "88.618762",
        "order_up_down": 3,
        "lat": "25.689237",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 31,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 34.36,
        "date_of_rhwl": "1987-08-14"
    },
    {
        "id": 75,
        "coords": "295,188",
        "name": "Kaunia",
        "river": "Teesta",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "29.31",
        "riverhighestwaterlevel": "30.06",
        "pmdl": None,
        "river_chainage": "TEESTA(79790.00)",
        "division": "Rangpur",
        "district": "Lalmonirhat",
        "upazilla": "Lalmonirhat Sadar",
        "union": "Gokunda",
        "long": "89.437306",
        "order_up_down": 5,
        "lat": "25.787864",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 3,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 30.42,
        "date_of_rhwl": "2020-10-07"
    },
    {
        "id": 76,
        "coords": "230,210",
        "name": "Badarganj",
        "river": "Jamuneswari",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "31.70",
        "riverhighestwaterlevel": "33.15",
        "pmdl": None,
        "river_chainage": "CJAMUNESWARI(108516.00)",
        "division": "Rangpur",
        "district": "Rangpur",
        "upazilla": "Taraganj",
        "union": "Kursha",
        "long": "89.062548",
        "order_up_down": 3,
        "lat": "25.675475",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 4,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 33.1,
        "date_of_rhwl": "2017-08-16"
    },
    {
        "id": 77,
        "coords": "336,182",
        "name": "Kurigram",
        "river": "Dharla",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "26.05",
        "riverhighestwaterlevel": "27.38",
        "pmdl": None,
        "river_chainage": "DHARLA(21500.00)",
        "division": "Rangpur",
        "district": "Kurigram",
        "upazilla": "Kurigram Sadar",
        "union": "Paurashava",
        "long": "89.667595",
        "order_up_down": 4,
        "lat": "25.820410",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 1,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 27.18,
        "date_of_rhwl": "2017-08-13"
    },
    {
        "id": 78,
        "coords": "354,163",
        "name": "Noonkhawa",
        "river": "Brahmaputra",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "26.05",
        "riverhighestwaterlevel": "27.61",
        "pmdl": None,
        "river_chainage": "JAMUNA(8000.00)",
        "division": "Rangpur",
        "district": "Kurigram",
        "upazilla": "Nageshwari",
        "union": "Kaliganj",
        "long": "89.766460",
        "order_up_down": 2,
        "lat": "25.920668",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 8,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 27.63,
        "date_of_rhwl": "1962-08-22"
    },
    {
        "id": 79,
        "coords": "208,245",
        "name": "Phulbari",
        "river": "Ichamati-Jamuna",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "29.50",
        "riverhighestwaterlevel": "30.01",
        "pmdl": None,
        "river_chainage": "ICH-JAMUNA(59000.00)",
        "division": "Rangpur",
        "district": "Dinajpur",
        "upazilla": "Birganj",
        "union": "Mohanpur",
        "long": "88.702683",
        "order_up_down": 2,
        "lat": "26.030516",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 32,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 30.01,
        "date_of_rhwl": "2001-10-07"
    },
    {
        "id": 80,
        "coords": "232,122",
        "name": "Dalia",
        "river": "Teesta",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "52.15",
        "riverhighestwaterlevel": "52.84",
        "pmdl": None,
        "river_chainage": "",
        "division": "Rangpur",
        "district": "Nilphamari",
        "upazilla": "Dimla",
        "union": "Khalisa Chapani",
        "long": "89.073729",
        "order_up_down": 1,
        "lat": "26.125276",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 2,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 52.9,
        "date_of_rhwl": "2021-10-20"
    },
    {
        "id": 81,
        "coords": "139,82",
        "name": "Panchagarh",
        "river": "Upper Karatoa",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "70.30",
        "riverhighestwaterlevel": "71.96",
        "pmdl": None,
        "river_chainage": "UKARATOYA(41500.00)",
        "division": "Rangpur",
        "district": "Panchagarh",
        "upazilla": "Panchagar Sadar",
        "union": "Panchagarh",
        "long": "88.544405",
        "order_up_down": 1,
        "lat": "26.330021",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 30,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 72.03,
        "date_of_rhwl": "1950-09-08"
    },
    {
        "id": 82,
        "coords": "48,416",
        "name": "Pankha",
        "river": "Ganges",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "22.05",
        "riverhighestwaterlevel": "23.68",
        "pmdl": None,
        "river_chainage": "GANGES-EXT(0.00)",
        "division": "Rajshahi",
        "district": "Chapai Nawabganj",
        "upazilla": "Shibganj",
        "union": "Panka",
        "long": "88.068931",
        "order_up_down": 10,
        "lat": "24.644253",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 39,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 23.67,
        "date_of_rhwl": "1998-09-07"
    },
    {
        "id": 83,
        "coords": "681,519",
        "name": "Ballah",
        "river": "Khowai",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "21.20",
        "riverhighestwaterlevel": "25.66",
        "pmdl": None,
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Habiganj",
        "upazilla": "Chunarughat",
        "union": "Ahmadabad",
        "long": "91.596150",
        "order_up_down": 19,
        "lat": "24.098525",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 63,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 25.74,
        "date_of_rhwl": "2001-06-06"
    },
    {
        "id": 84,
        "coords": "520,593",
        "name": "Bayderbazar",
        "river": "Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "4.70",
        "riverhighestwaterlevel": "6.78",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Narayanganj",
        "upazilla": "Araihazar",
        "union": "Bishnandi",
        "long": "90.700177",
        "order_up_down": 20,
        "lat": "23.719045",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 86,
        "coords": "725,467",
        "name": "Kamalganj",
        "river": "Dhalai",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "19.35",
        "riverhighestwaterlevel": "20.72",
        "pmdl": "19.05",
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Mouivibazar",
        "upazilla": "Kamalganj",
        "union": "Kamalganj",
        "long": "91.845820",
        "order_up_down": 21,
        "lat": "24.352029",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 65,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 20.27,
        "date_of_rhwl": "2019-06-14"
    },
    {
        "id": 87,
        "coords": "339,414",
        "name": "Kazipur",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "14.80",
        "riverhighestwaterlevel": "17.01",
        "pmdl": None,
        "river_chainage": "",
        "division": "Rajshahi",
        "district": "Sirajganj",
        "upazilla": "Kazipur",
        "union": "Tekani",
        "long": "89.689858",
        "order_up_down": 24,
        "lat": "24.635869",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 16.59,
        "date_of_rhwl": "2004-07-14"
    },
    {
        "id": 88,
        "coords": "441,642",
        "name": "Mawa",
        "river": "Padma",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "5.65",
        "riverhighestwaterlevel": "6.66",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Munshiganj",
        "upazilla": "Lohajang",
        "union": "Medini Mandal",
        "long": "90.256042",
        "order_up_down": 34,
        "lat": "23.470842",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 6.41,
        "date_of_rhwl": "1988-09-10"
    },
    {
        "id": 89,
        "coords": "510,620",
        "name": "Meghna-Br",
        "river": "Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "4.55",
        "riverhighestwaterlevel": "6.30",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Munshiganj",
        "upazilla": "Gazaria",
        "union": "Tenger Char",
        "long": "90.638969",
        "order_up_down": 22,
        "lat": "23.584570",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 90,
        "coords": "362,509",
        "name": "Porabari",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "11.80",
        "riverhighestwaterlevel": "18.23",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Tangail",
        "upazilla": "Nagarpur",
        "union": "Bhara",
        "long": "89.815249",
        "order_up_down": 25,
        "lat": "24.147259",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 18.55,
        "date_of_rhwl": "2012-09-30"
    },
    {
        "id": 91,
        "coords": "481,623",
        "name": "Rekabi-Bazar",
        "river": "Dhaleswari",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "4.75",
        "riverhighestwaterlevel": "6.41",
        "pmdl": None,
        "river_chainage": "",
        "division": "Dhaka",
        "district": "Narayanganj",
        "upazilla": "Narayanganj Sadar",
        "union": "Rekabi Bazar",
        "long": "90.480010",
        "order_up_down": 26,
        "lat": "23.562690",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 28,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 5.92,
        "date_of_rhwl": "1998-09-10"
    },
    {
        "id": 92,
        "coords": "232,545",
        "name": "Talbaria",
        "river": "Ganges",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "13.05",
        "riverhighestwaterlevel": "13.07",
        "pmdl": None,
        "river_chainage": "",
        "division": "Khulna",
        "district": "Kushtia",
        "upazilla": "Mirpur",
        "union": "Talbaria",
        "long": "89.092925",
        "order_up_down": 35,
        "lat": "23.961765",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 14.1,
        "date_of_rhwl": "1998-09-09"
    },
    {
        "id": 93,
        "coords": "123,139",
        "name": "Thakurgaon",
        "river": "Tangon",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "49.95",
        "riverhighestwaterlevel": "50.84",
        "pmdl": None,
        "river_chainage": "",
        "division": "Rangpur",
        "district": "Thakurgaon",
        "upazilla": "Thakurgaon Sadar",
        "union": "Nargun",
        "long": "88.460897",
        "order_up_down": 36,
        "lat": "26.037960",
        "forecast_observation": 2,
        "status": 1,
        "station_order": 33,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 50.87,
        "date_of_rhwl": "2017-08-13"
    },
    {
        "id": 94,
        "coords": "348,310",
        "name": "Dewanganj",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": None,
        "riverhighestwaterlevel": "20.62",
        "pmdl": None,
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Jamalpur",
        "upazilla": "Dewanganj",
        "union": "Chukaibari",
        "long": "89.730000",
        "order_up_down": 38,
        "lat": "25.160000",
        "forecast_observation": 3,
        "status": 1,
        "station_order": 10,
        "medium_range_station": 0,
        "unit_id": 1,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 95,
        "coords": "317,363",
        "name": "Sariakandi",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "16.25",
        "riverhighestwaterlevel": "18.61",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Bogra",
        "upazilla": "Sariakandi",
        "union": "Sariakandi",
        "long": "89.580654",
        "order_up_down": 39,
        "lat": "24.891637",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 12,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": 18.59,
        "date_of_rhwl": "1988-08-30"
    },
    {
        "id": 96,
        "coords": "642,385",
        "name": "Derai",
        "river": "Surma Old Course",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "6.55",
        "riverhighestwaterlevel": "7.29",
        "pmdl": "5.50",
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Sunamganj",
        "upazilla": "Derai",
        "union": "Derai Sarmangal",
        "long": "91.379531",
        "order_up_down": 40,
        "lat": "24.785555",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 66,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.29,
        "date_of_rhwl": "2008-07-24"
    },
    {
        "id": 97,
        "coords": "320,514",
        "name": "Baghabari",
        "river": "Karatoa-Atrai-GGH",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "9.95",
        "riverhighestwaterlevel": "11.99",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Sirajganj",
        "upazilla": "Shahjadpur",
        "union": "Potajia",
        "long": "89.582497",
        "order_up_down": 41,
        "lat": "24.129955",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 16,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.8,
        "date_of_rhwl": "2012-07-31"
    },
    {
        "id": 98,
        "coords": "529,556",
        "name": "Narsingdi",
        "river": "Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "5.25",
        "riverhighestwaterlevel": "6.55",
        "pmdl": "5.25",
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Narsingdi",
        "upazilla": "Narsingdi Sadar",
        "union": "Hajipur",
        "long": "90.726530",
        "order_up_down": 42,
        "lat": "23.918646",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 73,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 6.21,
        "date_of_rhwl": "2004-07-26"
    },
    {
        "id": 99,
        "coords": "645,402",
        "name": "Markuli",
        "river": "Surma-Meghna",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "7.05",
        "riverhighestwaterlevel": "8.05",
        "pmdl": "5.95",
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Sunamganj",
        "upazilla": "Derai",
        "union": "Kulanj",
        "long": "91.389698",
        "order_up_down": 43,
        "lat": "24.691644",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 59,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 7.48,
        "date_of_rhwl": "2008-08-03"
    },
    {
        "id": 100,
        "coords": "593,401",
        "name": "Khaliajuri",
        "river": "Dhanu",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "6.55",
        "riverhighestwaterlevel": "9.06",
        "pmdl": "4.15",
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Netrakona",
        "upazilla": "Khaliajuri",
        "union": "Chakua",
        "long": "91.110489",
        "order_up_down": 44,
        "lat": "24.702170",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 67,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 8.96,
        "date_of_rhwl": "2004-07-21"
    },
    {
        "id": 101,
        "coords": "512,530",
        "name": "Lakhpur",
        "river": "Lakhya",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "5.35",
        "riverhighestwaterlevel": "7.41",
        "pmdl": None,
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Gazipur",
        "upazilla": "Kapasia",
        "union": "Durgapur",
        "long": "90.650532",
        "order_up_down": 45,
        "lat": "24.040344",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 20,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 6.84,
        "date_of_rhwl": "1998-09-13"
    },
    {
        "id": 102,
        "coords": "331,548",
        "name": "Mathura",
        "river": "Brahmaputra-Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "9.60",
        "riverhighestwaterlevel": "11.44",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Pabna",
        "upazilla": "Bera",
        "union": "Jotsakhni",
        "long": "89.651210",
        "order_up_down": 46,
        "lat": "23.950299",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 11.08,
        "date_of_rhwl": "2007-08-03"
    },
    {
        "id": 103,
        "coords": "365,506",
        "name": "Elasinghat",
        "river": "Dhaleswari",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "10.95",
        "riverhighestwaterlevel": "12.34",
        "pmdl": None,
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Tangail",
        "upazilla": "Tangail Sadar",
        "union": "Katuli",
        "long": "89.835279",
        "order_up_down": 47,
        "lat": "24.167426",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 17,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 1,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 104,
        "coords": "256,466",
        "name": "Chanchkair",
        "river": "Karatoa-Atrai-GGH",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": None,
        "riverhighestwaterlevel": "13.24",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Natore",
        "upazilla": "Gurudaspur",
        "union": "Pourashava",
        "long": "89.226099",
        "order_up_down": 48,
        "lat": "24.374078",
        "forecast_observation": 3,
        "status": 1,
        "station_order": 15,
        "medium_range_station": 0,
        "unit_id": 1,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 105,
        "coords": "240,440",
        "name": "Singra",
        "river": "Gur",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "12.20",
        "riverhighestwaterlevel": "13.30",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Natore",
        "upazilla": "Singra",
        "union": "Singra Psa",
        "long": "89.140000",
        "order_up_down": None,
        "lat": "24.498000",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 12.84,
        "date_of_rhwl": "2020-10-01"
    },
    {
        "id": 108,
        "coords": "621,529",
        "name": "B. Baria",
        "river": "Titas",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "5.05",
        "riverhighestwaterlevel": "6.04",
        "pmdl": "5.05",
        "river_chainage": None,
        "division": "Chittagong",
        "district": "Brahmmonbaria",
        "upazilla": "B. Baria Sadar",
        "union": "Pouroshova",
        "long": "91.119442",
        "order_up_down": None,
        "lat": "23.956966",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 6.62,
        "date_of_rhwl": "2004-07-24"
    },
    {
        "id": 109,
        "coords": "345,130",
        "name": "Pateswari",
        "river": "Dudkumar",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "29.60",
        "riverhighestwaterlevel": "30.97",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rangpur",
        "district": "Kurigram",
        "upazilla": "Nageswari",
        "union": "Bamandanga",
        "long": "89.721537",
        "order_up_down": None,
        "lat": "26.096587",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 30.85,
        "date_of_rhwl": "2017-08-13"
    },
    {
        "id": 110,
        "coords": "324,311",
        "name": "Fulchari",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "19.35",
        "riverhighestwaterlevel": "20.23",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rangpur",
        "district": "Gaibandha",
        "upazilla": "Fulchari",
        "union": "Gazaria",
        "long": "89.589996",
        "order_up_down": None,
        "lat": "25.190001",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 110,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 20.69,
        "date_of_rhwl": "2019-07-18"
    },
    {
        "id": 111,
        "coords": "311,350",
        "name": "Shimulbari",
        "river": "Bangali",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "17.75",
        "riverhighestwaterlevel": "18.76",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rangpur",
        "district": "Gaibandha",
        "upazilla": "Gobindaganj",
        "union": "Salmara",
        "long": "89.519997",
        "order_up_down": None,
        "lat": "25.049999",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 18.37,
        "date_of_rhwl": "1988-08-31"
    },
    {
        "id": 112,
        "coords": "439,522",
        "name": "Kaliakoir",
        "river": "Turag",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "7.95",
        "riverhighestwaterlevel": "9.82",
        "pmdl": None,
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Gazipur",
        "upazilla": "Kaliakoir",
        "union": "Sutrapur",
        "long": "90.209999",
        "order_up_down": None,
        "lat": "24.080000",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.29,
        "date_of_rhwl": "1988-09-03"
    },
    {
        "id": 113,
        "coords": "462,807",
        "name": "Barisal",
        "river": "Kirtonkhola",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "2.10",
        "riverhighestwaterlevel": "2.74",
        "pmdl": None,
        "river_chainage": None,
        "division": "Barisal",
        "district": "Barisal",
        "upazilla": "Barisal Sadar",
        "union": "Char Kowa",
        "long": "90.349999",
        "order_up_down": None,
        "lat": "22.670000",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 114,
        "coords": "364,735",
        "name": "Haridaspur",
        "river": "Madaripur BR",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": "3.35",
        "riverhighestwaterlevel": "4.59",
        "pmdl": None,
        "river_chainage": None,
        "division": "Dhaka",
        "district": "Gopalganj",
        "upazilla": "Gopalganj Sadar",
        "union": "Haridaspur",
        "long": "89.820000",
        "order_up_down": None,
        "lat": "23.030001",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 40,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 4.02,
        "date_of_rhwl": "1998-09-13"
    },
    {
        "id": 116,
        "coords": "364,735",
        "name": "Demo",
        "river": "Mohananda",
        "basin_order": 2,
        "basin": "Ganges Basin",
        "dangerlevel": None,
        "riverhighestwaterlevel": "5.00",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rajshahi",
        "district": "Chapai Nawabganj",
        "upazilla": "Shibganj",
        "union": "Shibganj Union",
        "long": "88.132810",
        "order_up_down": None,
        "lat": "24.798774",
        "forecast_observation": 1,
        "status": 1,
        "station_order": 40,
        "medium_range_station": 0,
        "unit_id": 1,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 117,
        "coords": "341,207",
        "name": "Hatia",
        "river": "Brahmaputra",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "24.40",
        "riverhighestwaterlevel": "25.84",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rangpur",
        "district": "Kurigram",
        "upazilla": "Ulipur",
        "union": "Hatia",
        "long": "89.691960",
        "order_up_down": None,
        "lat": "25.680280",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 25.61,
        "date_of_rhwl": "2022-06-21"
    },
    {
        "id": 118,
        "coords": "322,326",
        "name": "Saghata",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "18.50",
        "riverhighestwaterlevel": "21.20",
        "pmdl": None,
        "river_chainage": None,
        "division": "Rangpur",
        "district": "Gaibandha",
        "upazilla": "Saghata",
        "union": "Saghata",
        "long": "89.586564",
        "order_up_down": None,
        "lat": "25.107540",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 21.2,
        "date_of_rhwl": "2021-09-03"
    },
    {
        "id": 119,
        "coords": "725,869",
        "name": "Chittagong",
        "river": "Karnaphuli",
        "basin_order": 4,
        "basin": "South Eastern Hill Basin",
        "dangerlevel": "4.15",
        "riverhighestwaterlevel": "4.52",
        "pmdl": None,
        "river_chainage": None,
        "division": "Chittagong",
        "district": "Chittagong",
        "upazilla": "Double Mooring",
        "union": "Double Mooring",
        "long": "91.828700",
        "order_up_down": None,
        "lat": "22.322900",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": None,
        "date_of_rhwl": None
    },
    {
        "id": 120,
        "coords": "550,330",
        "name": "Kalmakanda",
        "river": "Someswari",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "6.55",
        "riverhighestwaterlevel": "12.81",
        "pmdl": "4.90",
        "river_chainage": None,
        "division": "Mymensingh",
        "district": "Netrakona",
        "upazilla": "Kalmakanda",
        "union": "Kalmakanda",
        "long": "90.879997",
        "order_up_down": None,
        "lat": "25.096001",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 1,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 12.6,
        "date_of_rhwl": "2006-05-31"
    },
    {
        "id": 121,
        "coords": "518,312",
        "name": "Bijoypur",
        "river": "Someswari",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "13.20",
        "riverhighestwaterlevel": None,
        "pmdl": "14.30",
        "river_chainage": None,
        "division": "Mymensingh",
        "district": "Netrakona",
        "upazilla": "Durgapur",
        "union": "Kullagora",
        "long": "90.669998",
        "order_up_down": None,
        "lat": "25.168699",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 17.55,
        "date_of_rhwl": "2007-07-28"
    },
    {
        "id": 122,
        "coords": "641,316",
        "name": "Muslimpur",
        "river": "Jhalukhali",
        "basin_order": 3,
        "basin": "Meghna Basin",
        "dangerlevel": "7.75",
        "riverhighestwaterlevel": None,
        "pmdl": None,
        "river_chainage": None,
        "division": "Sylhet",
        "district": "Sunamganj",
        "upazilla": "Sunamganj Sadar",
        "union": "",
        "long": "91.389999",
        "order_up_down": None,
        "lat": "25.138700",
        "forecast_observation": 1,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 9.25,
        "date_of_rhwl": "2003-06-30"
    },
    {
        "id": 123,
        "coords": "353,415",
        "name": "Jagannathganj",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "13.55",
        "riverhighestwaterlevel": None,
        "pmdl": None,
        "river_chainage": None,
        "division": "Mymensingh",
        "district": "Jamalpur",
        "upazilla": "Sarishabari",
        "union": "Jagannathganj",
        "long": "89.809998",
        "order_up_down": 24,
        "lat": "24.654400",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 0.0,
        "date_of_rhwl": "0000-00-00"
    },
    {
        "id": 124,
        "coords": "353,415",
        "name": "Jagannathganj",
        "river": "Jamuna",
        "basin_order": 1,
        "basin": "Brahmaputra Basin",
        "dangerlevel": "13.55",
        "riverhighestwaterlevel": None,
        "pmdl": None,
        "river_chainage": None,
        "division": "Mymensingh",
        "district": "Jamalpur",
        "upazilla": "Sarishabari",
        "union": "Jagannathganj",
        "long": "89.809998",
        "order_up_down": 24,
        "lat": "24.654400",
        "forecast_observation": 2,
        "status": 1,
        "station_order": None,
        "medium_range_station": 0,
        "unit_id": 2,
        "jason_2_satellie_station": 0,
        "rhwl": 0.0,
        "date_of_rhwl": "0000-00-00"
    }
]
